import { NextResponse } from "next/server";
import { verifyBearer } from "@/lib/auth/bearer";
import { appUrl } from "@/lib/auth/app-url";
import { CLOUD_INIT_SCRIPT_BODY } from "@/lib/deploy/cloud-init-script";

export const dynamic = "force-dynamic";

/**
 * GET /api/deploy/cloud-init?token=<JWT>&model=<name>
 *
 * Serves the universal provider bootstrap script as text/x-shellscript so
 * cloud-init / wget / curl pipelines can pipe it directly into bash:
 *
 *   curl -fsSL "https://infernetprotocol.com/api/deploy/cloud-init?token=$TOKEN" | bash
 *
 * Script body lives in @/lib/deploy/cloud-init-script (inlined as a
 * string so the runtime image doesn't need the source `tooling/`
 * directory). The on-disk source-of-truth is
 * tooling/cloud-init/infernet-provider.sh; tests/cloud-init-script.test.js
 * enforces byte-equality so the two can't drift.
 *
 * If a `token` query param verifies as a CLI bearer JWT, we inject
 * INFERNET_BEARER + INFERNET_CONTROL_PLANE as env exports at the top
 * so the bootstrapped node auto-links to the issuing user's account.
 * Missing/invalid tokens still get the script — just without the
 * auto-link (operator can `infernet pubkey link` later).
 */
export async function GET(request) {
    const url = new URL(request.url);
    const token = url.searchParams.get("token");
    const model = url.searchParams.get("model") ?? null;

    const claims = token ? verifyBearer(token) : null;
    const controlPlane = appUrl();

    const exports = [];
    if (claims?.sub) {
        exports.push(`export INFERNET_BEARER=${shellQuote(token)}`);
        exports.push(
            `# bearer issued for user ${claims.sub}, expires ${claims.exp ? new Date(claims.exp * 1000).toISOString() : "(no exp)"}`
        );
    }
    exports.push(`export INFERNET_CONTROL_PLANE=${shellQuote(controlPlane)}`);
    if (model) exports.push(`export INFERNET_MODEL=${shellQuote(model)}`);

    const out =
        `#!/usr/bin/env bash\n` +
        `# Generated by ${controlPlane}/api/deploy/cloud-init at ${new Date().toISOString()}\n` +
        exports.join("\n") + "\n\n" +
        CLOUD_INIT_SCRIPT_BODY;

    return new NextResponse(out, {
        status: 200,
        headers: {
            "content-type": "text/x-shellscript; charset=utf-8",
            "cache-control": "no-store"
        }
    });
}

function shellQuote(s) {
    if (s == null) return "''";
    return "'" + String(s).replace(/'/g, "'\\''") + "'";
}
