import { NextResponse } from "next/server";
import { readFile } from "node:fs/promises";
import { verifyBearer } from "@/lib/auth/bearer";
import { appUrl } from "@/lib/auth/app-url";

export const dynamic = "force-dynamic";

/**
 * GET /api/deploy/cloud-init?token=<JWT>&model=<name>
 *
 * Universal bootstrap — returns the canonical `install.sh` with
 * caller-supplied env exports prepended. Same script that runs on
 * a manual `curl … /install.sh | sh` install on bare metal also
 * runs inside RunPod / DigitalOcean / cloud-init contexts; the
 * difference is just the env vars we prepend.
 *
 * Why this exists at all (vs pointing operators directly at
 * /install.sh): we mint the per-user 24h INFERNET_BEARER on the
 * server side and weave it into the script's env exports here, so
 * a single curl-pipe-bash invocation auto-links the new node to
 * the issuing user's account without the operator copy-pasting
 * the token into a separate command.
 *
 * Idempotent: install.sh skips work that's already done (Node 18+
 * present, packages installed, repo cloned). Re-running the
 * cloud-init URL on a healthy box is safe and fast.
 */
export async function GET(request) {
    const url = new URL(request.url);
    const token = url.searchParams.get("token");
    const model = url.searchParams.get("model") ?? null;

    const installSh = await readFile(
        new URL("../../../../public/install.sh", import.meta.url),
        "utf8"
    ).catch(() => null);

    if (!installSh) {
        return new NextResponse("# install.sh not found on this deploy\n", {
            status: 500,
            headers: { "content-type": "text/plain; charset=utf-8" }
        });
    }

    const claims = token ? verifyBearer(token) : null;
    const controlPlane = appUrl();

    const exports = [];
    if (claims?.sub) {
        exports.push(`export INFERNET_BEARER=${shellQuote(token)}`);
        exports.push(
            `# bearer issued for user ${claims.sub}, expires ${claims.exp ? new Date(claims.exp * 1000).toISOString() : "(no exp)"}`
        );
    }
    exports.push(`export INFERNET_CONTROL_PLANE=${shellQuote(controlPlane)}`);
    if (model) exports.push(`export INFERNET_MODEL=${shellQuote(model)}`);
    exports.push(`export INFERNET_NONINTERACTIVE=1`);

    // Strip the install.sh shebang and prepend our own header + env
    // exports. The rest of the script is byte-identical to
    // /install.sh so behavior stays consistent across paths.
    // install.sh is POSIX-sh-compatible — match its shebang so
    // `curl … | sh` works the same as `curl … | bash`.
    const stripped = installSh.replace(/^#!.*?\n/, "");
    const out =
        `#!/bin/sh\n` +
        `# Generated by ${controlPlane}/api/deploy/cloud-init at ${new Date().toISOString()}\n` +
        exports.join("\n") + "\n\n" +
        stripped;

    return new NextResponse(out, {
        status: 200,
        headers: {
            "content-type": "text/x-shellscript; charset=utf-8",
            "cache-control": "no-store"
        }
    });
}

function shellQuote(s) {
    if (s == null) return "''";
    return "'" + String(s).replace(/'/g, "'\\''") + "'";
}
