import { NextResponse } from "next/server";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { verifyBearer } from "@/lib/auth/bearer";
import { appUrl } from "@/lib/auth/app-url";

export const dynamic = "force-dynamic";

/**
 * GET /api/deploy/cloud-init?token=<JWT>
 *
 * Serves the universal provider bootstrap script as text/x-shellscript so
 * cloud-init / wget / curl pipelines can pipe it directly into bash:
 *
 *   curl -fsSL "https://infernetprotocol.com/api/deploy/cloud-init?token=$TOKEN" | bash
 *
 * The script itself lives at tooling/cloud-init/infernet-provider.sh.
 * If a `token` query param is present and verifies as a CLI bearer JWT,
 * we inject INFERNET_BEARER + INFERNET_CONTROL_PLANE as env exports at
 * the top of the script so the bootstrapped node auto-links to the
 * issuing user's account.
 *
 * If the token is missing or invalid we still serve the script — it
 * just won't auto-link the node to an account, which is fine for
 * users who self-host or want to claim the pubkey later via
 * `infernet pubkey link`.
 */
export async function GET(request) {
    const url = new URL(request.url);
    const token = url.searchParams.get("token");
    const model = url.searchParams.get("model") ?? null;

    let scriptText;
    try {
        const path = join(process.cwd(), "../../tooling/cloud-init/infernet-provider.sh");
        scriptText = await readFile(path, "utf8");
    } catch {
        // Fallback for prod where cwd may differ from the dev path.
        const path = join(process.cwd(), "tooling/cloud-init/infernet-provider.sh");
        scriptText = await readFile(path, "utf8").catch(() => null);
    }

    if (!scriptText) {
        return new NextResponse("# infernet-provider.sh not found on this deploy\n", {
            status: 500,
            headers: { "content-type": "text/plain; charset=utf-8" }
        });
    }

    const claims = token ? verifyBearer(token) : null;
    const controlPlane = appUrl();
    const exports = [];
    if (claims?.sub) {
        exports.push(`export INFERNET_BEARER=${shellQuote(token)}`);
        exports.push(`# bearer issued for user ${claims.sub}, expires ${claims.exp ? new Date(claims.exp * 1000).toISOString() : "(no exp)"}`);
    }
    exports.push(`export INFERNET_CONTROL_PLANE=${shellQuote(controlPlane)}`);
    if (model) exports.push(`export INFERNET_MODEL=${shellQuote(model)}`);

    const header = `#!/usr/bin/env bash
# Generated by ${controlPlane}/api/deploy/cloud-init at ${new Date().toISOString()}
${exports.join("\n")}
`;

    // Strip the original shebang and any "set -euo pipefail" duplication —
    // we'll prepend our own header that includes the env exports.
    const stripped = scriptText.replace(/^#!.*?\n/, "");

    const out = header + stripped;

    return new NextResponse(out, {
        status: 200,
        headers: {
            "content-type": "text/x-shellscript; charset=utf-8",
            // Don't cache — every request might want a different bearer.
            "cache-control": "no-store"
        }
    });
}

function shellQuote(s) {
    if (s == null) return "''";
    // Single-quote the value, escape any embedded single quotes.
    return "'" + String(s).replace(/'/g, "'\\''") + "'";
}
