/**
 * Generate a Python QLoRA training script using Unsloth.
 *
 * Unsloth is the de-facto standard for fast 4-bit LoRA fine-tuning on
 * consumer GPUs (https://github.com/unslothai/unsloth). We generate a
 * self-contained script per run, parameterized by the YAML config; the
 * script is what `infernet train run` and the daemon's train_shard
 * handler both invoke.
 *
 * The output script:
 *   - loads the base model in 4-bit
 *   - applies LoRA to attention projections
 *   - reads ChatML-format JSONL from --data
 *   - trains for the configured epochs
 *   - saves checkpoint-final/ as a HF-shape directory (adapter + tokenizer)
 *   - writes per-step metrics.jsonl alongside
 */

export function buildUnslothScript({ trainConfig }) {
    const baseModel = trainConfig.base_model ?? "unsloth/Qwen2.5-7B-Instruct";
    const epochs = trainConfig.training?.epochs ?? 3;
    const lr = trainConfig.training?.learning_rate ?? 2e-4;
    const batchSize = trainConfig.training?.batch_size ?? 4;
    const gradAccum = trainConfig.training?.gradient_accumulation_steps ?? 4;
    const maxSeqLen = trainConfig.training?.max_seq_len ?? 4096;
    const seed = trainConfig.training?.seed ?? 42;
    const loraR = trainConfig.lora?.rank ?? 16;
    const loraAlpha = trainConfig.lora?.alpha ?? 32;
    const loraDropout = trainConfig.lora?.dropout ?? 0.05;
    const targetModules = JSON.stringify(trainConfig.lora?.target_modules ?? ["q_proj", "k_proj", "v_proj", "o_proj"]);

    return `#!/usr/bin/env python3
"""Unsloth QLoRA fine-tune — generated by \`infernet train run\`."""

import argparse
import json
import os
import sys
import time
from pathlib import Path


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--data", required=True, help="JSONL dataset (chatml messages)")
    p.add_argument("--output", required=True, help="Output dir for checkpoints + metrics")
    p.add_argument("--base-model", default=${JSON.stringify(baseModel)})
    args = p.parse_args()

    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    metrics_path = output / "metrics.jsonl"

    # Imports kept here so a missing dep fails loudly with a clear hint
    # instead of crashing at module-import time before logging anything.
    try:
        from unsloth import FastLanguageModel
        from unsloth.chat_templates import standardize_sharegpt, get_chat_template
        from datasets import load_dataset
        from transformers import TrainingArguments
        from trl import SFTTrainer
        import torch
    except ImportError as e:
        print(json.dumps({"error": f"missing dependency: {e}. Install with: pip install unsloth datasets trl"}), flush=True)
        sys.exit(2)

    print(json.dumps({"event": "loading_model", "base_model": args.base_model}), flush=True)
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.base_model,
        max_seq_length=${maxSeqLen},
        dtype=None,           # auto-detect bf16/fp16
        load_in_4bit=True,
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r=${loraR},
        lora_alpha=${loraAlpha},
        lora_dropout=${loraDropout},
        target_modules=${targetModules},
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=${seed},
    )

    # ChatML template (works for Qwen, Llama 3 chat, most modern fine-tunes)
    tokenizer = get_chat_template(tokenizer, chat_template="chatml")

    print(json.dumps({"event": "loading_dataset", "path": args.data}), flush=True)
    dataset = load_dataset("json", data_files=args.data, split="train")

    def format_examples(examples):
        texts = []
        for msgs in examples["messages"]:
            text = tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=False)
            texts.append(text)
        return {"text": texts}

    dataset = dataset.map(format_examples, batched=True)
    print(json.dumps({"event": "dataset_ready", "rows": len(dataset)}), flush=True)

    training_args = TrainingArguments(
        output_dir=str(output),
        per_device_train_batch_size=${batchSize},
        gradient_accumulation_steps=${gradAccum},
        num_train_epochs=${epochs},
        learning_rate=${lr},
        warmup_steps=10,
        logging_steps=5,
        save_steps=200,
        save_total_limit=2,
        seed=${seed},
        bf16=torch.cuda.is_bf16_supported(),
        fp16=not torch.cuda.is_bf16_supported(),
        optim="adamw_8bit",
        report_to="none",
    )

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=${maxSeqLen},
        args=training_args,
        packing=False,
    )

    # Stream logs as JSONL into metrics.jsonl
    metrics_f = open(metrics_path, "a")
    last_step = -1
    t0 = time.time()

    class JsonLogger:
        def on_log(self, args, state, control, logs=None, **kw):
            nonlocal last_step
            if not logs or state.global_step == last_step:
                return
            last_step = state.global_step
            row = {
                "step": state.global_step,
                "loss": logs.get("loss"),
                "lr": logs.get("learning_rate"),
                "epoch": logs.get("epoch"),
                "elapsed_s": round(time.time() - t0, 2),
            }
            metrics_f.write(json.dumps(row) + "\\n")
            metrics_f.flush()
            print(json.dumps({"event": "step", **row}), flush=True)

    trainer.add_callback(JsonLogger())

    print(json.dumps({"event": "training_start", "epochs": ${epochs}}), flush=True)
    result = trainer.train()
    print(json.dumps({"event": "training_done", "loss": float(result.training_loss)}), flush=True)

    final_dir = output / "checkpoint-final"
    model.save_pretrained(str(final_dir))
    tokenizer.save_pretrained(str(final_dir))
    print(json.dumps({"event": "saved", "path": str(final_dir)}), flush=True)
    metrics_f.close()


if __name__ == "__main__":
    main()
`;
}
