/**
 * Book TOC accessor — used only by /book landing + sidebar nav.
 *
 * Chapters themselves are static .html files under apps/web/public/book/
 * generated by pandoc in .github/workflows/book.yml. Nothing in
 * apps/web reads chapter content at runtime; the .html files are
 * served straight off disk.
 */

import data from "./book-data.json" with { type: "json" };

export function getBookToc() {
    return data.toc ?? [];
}

export function getBookIntro() {
    return data.intro ?? "";
}
