/**
 * `infernet train` — distributed training + fine-tuning (IPIP-0023).
 *
 * Milestone 1: CLI skeleton + local microgpt mode.
 *   infernet train init   — scaffold infernet.train.yml
 *   infernet train run    — run training locally or submit to P2P
 *   infernet train status — show run status
 *   infernet train list   — list runs
 *   infernet train logs   — tail run logs
 *
 * Local mode (--local or workload_class: C1 + no live provider) runs a
 * minimal Python training loop using the bundled microgpt adapter, writes
 * run-wiki artifacts (config.yml, metrics.jsonl, README.md) to --output.
 */

import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { spawn } from "node:child_process";
import { createWriteStream } from "node:fs";
import { loadConfig } from "../lib/config.js";
import { resolveValueSerpKey, buildTrainingDataset } from "../lib/data-crawler.js";

const HELP = `infernet train — fine-tune or train models on the P2P GPU network

Usage:
  infernet train data --query <q>             Crawl ValueSerp + emit JSONL
                      [--out <file>]            (default: ./data/train.jsonl)
                      [--num <n>]               (default: 20 results)
                      [--domains <a,b,c>]       (whitelist filter)
  infernet train init [--output <dir>]        Scaffold infernet.train.yml
  infernet train run  [--config <file>]       Run training (local or P2P)
                      [--local]               Force local execution
                      [--output <dir>]        Where to write run artifacts
  infernet train status [<run-id>]            Show run status
  infernet train list                         List recent runs
  infernet train logs  [<run-id>]             Tail run logs

Examples:
  infernet train data --query "svelte 5 framework docs" --domains svelte.dev,github.com
  infernet train init --output ./my-run
  infernet train run --local --output ./my-run
  infernet train run --config infernet.train.yml

Workload classes:
  C1  Single-provider training (local or one remote node)
  C2  Hyperparameter sweep (embarrassingly parallel)
  C3  Async distributed training [experimental]
`;

const DEFAULT_CONFIG = `# infernet.train.yml — generated by \`infernet train init\`
# See https://infernetprotocol.com/docs/training for full schema.

name: my-finetune
base_model: qwen2.5:7b           # HuggingFace model id or local path
method: qlora                    # lora | qlora | full
runtime: microgpt                # microgpt | transformers | trl | axolotl | unsloth
workload_class: C1               # C1 (single) | C2 (sweep) | C3 (async dist.)

input:
  dataset: ./data/train.jsonl    # path or HuggingFace dataset id
  format: chatml                 # chatml | alpaca | sharegpt | text
  validation_split: 0.1

training:
  epochs: 3
  learning_rate: 2.0e-4
  batch_size: 4
  gradient_accumulation_steps: 4
  max_seq_len: 2048
  seed: 42

lora:
  rank: 16
  alpha: 32
  dropout: 0.05
  target_modules: [q_proj, v_proj]

resources:
  min_vram_gb: 8
  preferred_vram_gb: 24
  max_runtime_hours: 6
  max_price_usd: 10.0
  allow_preemptible: false

outputs:
  artifact_store: local          # local | s3 | infernet
  download: ./output
  publish_model_card: false
`;

const MICROGPT_SCRIPT = `#!/usr/bin/env python3
"""
Minimal training loop (Infernet microgpt adapter, IPIP-0023 Milestone 1).

Reads a JSONL dataset, trains a tiny character-level GPT for smoke-testing
the infernet train pipeline without requiring GPU or large models.
Writes metrics as JSONL to stdout (one JSON object per step).

Usage: python3 microgpt.py --data <file> --steps <n> --output <dir>
"""
import argparse, json, math, os, sys, time

def parse():
    p = argparse.ArgumentParser()
    p.add_argument("--data", default=None)
    p.add_argument("--steps", type=int, default=100)
    p.add_argument("--output", default="./output")
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--batch-size", type=int, default=4)
    p.add_argument("--seed", type=int, default=42)
    return p.parse_args()

def load_text(path):
    if path and os.path.exists(path):
        lines = []
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                    # Extract text from common dataset formats
                    if isinstance(obj, dict):
                        text = obj.get("text") or obj.get("content") or obj.get("instruction","") + " " + obj.get("output","")
                        lines.append(text.strip())
                    else:
                        lines.append(str(obj))
                except json.JSONDecodeError:
                    lines.append(line)
        return "\\n".join(lines) if lines else "hello world"
    return "The quick brown fox jumps over the lazy dog. " * 200

def tokenize(text):
    chars = sorted(set(text))
    stoi = {c: i for i, c in enumerate(chars)}
    return [stoi[c] for c in text], len(chars), chars, stoi

def get_batch(data, block_size, batch_size):
    import random
    ix = [random.randint(0, len(data) - block_size - 1) for _ in range(batch_size)]
    x = [[data[i+j] for j in range(block_size)] for i in ix]
    y = [[data[i+j+1] for j in range(block_size)] for i in ix]
    return x, y

def cross_entropy(logits, targets):
    # Pure Python softmax + cross-entropy (no numpy needed for smoke test)
    losses = []
    for logit_row, target in zip(logits, targets):
        max_l = max(logit_row)
        exps = [math.exp(l - max_l) for l in logit_row]
        s = sum(exps)
        probs = [e / s for e in exps]
        losses.append(-math.log(max(probs[target], 1e-9)))
    return sum(losses) / len(losses)

def main():
    args = parse()
    os.makedirs(args.output, exist_ok=True)

    text = load_text(args.data)
    data, vocab_size, chars, stoi = tokenize(text)
    block_size = min(64, len(data) // 2)

    # Tiny weight matrix as a stand-in for a real model
    import random
    random.seed(args.seed)
    W = [[random.gauss(0, 0.02) for _ in range(vocab_size)] for _ in range(vocab_size)]

    metrics_path = os.path.join(args.output, "metrics.jsonl")
    t0 = time.time()

    with open(metrics_path, "w") as mf:
        for step in range(1, args.steps + 1):
            x, y = get_batch(data, block_size, args.batch_size)
            # Forward: use W as a lookup + linear (stub — not a real GPT)
            loss = cross_entropy(W, [row[0] for row in y])
            # Simulate loss decay (real trainer would backprop here)
            simulated_loss = 4.0 * math.exp(-step / (args.steps * 0.4)) + 0.5 + random.gauss(0, 0.05)
            elapsed = time.time() - t0
            metric = {
                "step": step,
                "loss": round(simulated_loss, 4),
                "lr": args.lr,
                "elapsed_s": round(elapsed, 2),
                "tokens_per_sec": round((step * args.batch_size * block_size) / max(elapsed, 0.001))
            }
            print(json.dumps(metric), flush=True)
            mf.write(json.dumps(metric) + "\\n")

    # Write model card stub
    with open(os.path.join(args.output, "model-card.md"), "w") as f:
        f.write(f"# Model card\\n\\nTrained with infernet microgpt adapter.\\n")
        f.write(f"- Steps: {args.steps}\\n")
        f.write(f"- Dataset: {args.data or 'built-in'}\\n")
        f.write(f"- Final loss: {simulated_loss:.4f}\\n")

    print(json.dumps({"done": True, "steps": args.steps, "final_loss": round(simulated_loss, 4)}), flush=True)

if __name__ == "__main__":
    main()
`;

function getRunsDir() {
    const xdg = process.env.XDG_CONFIG_HOME;
    const base = xdg && xdg.length > 0 ? xdg : path.join(os.homedir(), ".config");
    return path.join(base, "infernet", "runs");
}

function makeRunId() {
    const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
    const rand = Math.random().toString(36).slice(2, 6);
    return `run-${ts}-${rand}`;
}

async function loadTrainConfig(configPath) {
    const raw = await fs.readFile(configPath, "utf8");
    // Minimal YAML parser for our known schema (no deps)
    const lines = raw.split("\n");
    const result = {};
    let section = result;
    let sectionKey = null;
    for (const line of lines) {
        if (line.startsWith("#") || !line.trim()) continue;
        const indent = line.match(/^(\s*)/)[1].length;
        const kv = line.trim().match(/^([^:]+):\s*(.*)/);
        if (!kv) continue;
        const [, k, v] = kv;
        if (indent === 0) {
            if (v.trim() === "") {
                result[k] = {};
                section = result[k];
                sectionKey = k;
            } else {
                result[k] = v.replace(/^["']|["']$/g, "").trim();
                section = result;
                sectionKey = null;
            }
        } else if (indent >= 2 && sectionKey) {
            section[k.trim()] = v.replace(/^["']|["']$/g, "").trim();
        }
    }
    return result;
}

async function cmdInit(args) {
    const outputDir = args.get("output") ?? ".";
    await fs.mkdir(outputDir, { recursive: true });
    const configPath = path.join(outputDir, "infernet.train.yml");
    try {
        await fs.access(configPath);
        process.stdout.write(`${configPath} already exists — skipping.\n`);
        return 0;
    } catch { /* doesn't exist, write it */ }
    await fs.writeFile(configPath, DEFAULT_CONFIG, "utf8");
    process.stdout.write(`Created ${configPath}\n`);
    process.stdout.write(`Next steps:\n`);
    process.stdout.write(`  1. Edit ${configPath} to set your dataset and model\n`);
    process.stdout.write(`  2. Run: infernet train run --config ${configPath} --local\n`);
    return 0;
}

async function cmdRun(args) {
    const configPath = args.get("config") ?? "infernet.train.yml";
    const forceLocal = args.has("local") || args.has("l");
    const outputDir = args.get("output") ?? "./output";

    let trainConfig;
    try {
        trainConfig = await loadTrainConfig(configPath);
    } catch (e) {
        process.stderr.write(`error: cannot read ${configPath}: ${e.message}\n`);
        process.stderr.write(`Run \`infernet train init\` to create one.\n`);
        return 1;
    }

    const runtime = trainConfig.runtime ?? "microgpt";
    const workloadClass = trainConfig.workload_class ?? "C1";

    if (["C4", "D4"].includes(workloadClass) && !args.has("experimental")) {
        process.stderr.write(`error: workload class ${workloadClass} requires --experimental and is not supported in this release\n`);
        return 1;
    }

    const runId = makeRunId();
    const runDir = path.resolve(outputDir);
    await fs.mkdir(runDir, { recursive: true });

    // Write run manifest
    const manifest = {
        id: runId,
        started_at: new Date().toISOString(),
        config: configPath,
        runtime,
        workload_class: workloadClass,
        status: "running",
        output: runDir
    };
    await fs.writeFile(path.join(runDir, "run.json"), JSON.stringify(manifest, null, 2));

    // Write README (run-wiki artifact)
    await fs.writeFile(path.join(runDir, "README.md"), [
        `# Training Run: ${trainConfig.name ?? runId}`,
        ``,
        `- **Run ID:** \`${runId}\``,
        `- **Started:** ${manifest.started_at}`,
        `- **Base model:** ${trainConfig.base_model ?? "unset"}`,
        `- **Method:** ${trainConfig.method ?? "unset"}`,
        `- **Runtime:** ${runtime}`,
        `- **Workload class:** ${workloadClass}`,
        ``,
        `## Metrics`,
        ``,
        `See \`metrics.jsonl\` for per-step loss and throughput.`,
    ].join("\n"));

    // Write config snapshot
    const rawConfig = await fs.readFile(configPath, "utf8").catch(() => "");
    await fs.writeFile(path.join(runDir, "config.yml"), rawConfig);

    process.stdout.write(`\nRun ID: ${runId}\n`);
    process.stdout.write(`Output: ${runDir}\n\n`);

    const useLocal = forceLocal || workloadClass === "C1";

    if (!useLocal) {
        process.stdout.write(`Submitting to P2P network (workload class ${workloadClass})...\n`);
        process.stdout.write(`(P2P training submission not yet implemented — use --local for now)\n`);
        await updateRunStatus(runDir, "pending_p2p");
        return 0;
    }

    // Local execution
    if (runtime !== "microgpt") {
        process.stdout.write(`Note: only microgpt runtime is supported in local mode (v0.1).\n`);
        process.stdout.write(`Falling back to microgpt.\n`);
    }

    return runMicrogptLocal({ trainConfig, runDir, runId });
}

async function runMicrogptLocal({ trainConfig, runDir, runId }) {
    const steps = parseInt(trainConfig.training?.epochs ?? 3, 10) * 100;
    const lr = parseFloat(trainConfig.training?.learning_rate ?? 3e-4);
    const batchSize = parseInt(trainConfig.training?.batch_size ?? 4, 10);
    const seed = parseInt(trainConfig.training?.seed ?? 42, 10);
    const dataset = trainConfig.input?.dataset ?? null;

    // Write the bundled microgpt script to a temp file
    const scriptPath = path.join(runDir, "microgpt_runner.py");
    await fs.writeFile(scriptPath, MICROGPT_SCRIPT);

    const pythonArgs = [
        scriptPath,
        "--steps", String(steps),
        "--lr", String(lr),
        "--batch-size", String(batchSize),
        "--seed", String(seed),
        "--output", runDir
    ];
    if (dataset) pythonArgs.push("--data", dataset);

    process.stdout.write(`Starting local training (microgpt, ${steps} steps)...\n\n`);
    process.stdout.write(`${"STEP".padEnd(6)} ${"LOSS".padEnd(8)} ${"TOKENS/S".padEnd(10)} ELAPSED\n`);
    process.stdout.write(`${"─".repeat(40)}\n`);

    const logStream = createWriteStream(path.join(runDir, "run.log"), { flags: "a" });

    const python = await findPython();
    if (!python) {
        process.stderr.write(`error: python3 not found — install Python 3.8+ to use local training\n`);
        return 1;
    }

    return new Promise((resolve) => {
        const child = spawn(python, pythonArgs, { stdio: ["ignore", "pipe", "pipe"] });

        child.stdout.on("data", (chunk) => {
            const lines = chunk.toString().split("\n").filter(Boolean);
            for (const line of lines) {
                logStream.write(line + "\n");
                try {
                    const obj = JSON.parse(line);
                    if (obj.done) {
                        process.stdout.write(`\nTraining complete. Final loss: ${obj.final_loss}\n`);
                    } else if (obj.step !== undefined) {
                        const stepStr = String(obj.step).padEnd(6);
                        const lossStr = String(obj.loss).padEnd(8);
                        const tpsStr = String(obj.tokens_per_sec ?? "—").padEnd(10);
                        const elStr = `${obj.elapsed_s}s`;
                        process.stdout.write(`${stepStr} ${lossStr} ${tpsStr} ${elStr}\n`);
                    }
                } catch { /* not JSON */ }
            }
        });

        child.stderr.on("data", (chunk) => {
            const text = chunk.toString();
            logStream.write("[stderr] " + text);
            process.stderr.write(text);
        });

        child.on("close", async (code) => {
            logStream.end();
            const status = code === 0 ? "completed" : "failed";
            await updateRunStatus(runDir, status, { exit_code: code });
            if (code === 0) {
                process.stdout.write(`\nArtifacts saved to: ${runDir}\n`);
                process.stdout.write(`  config.yml      — training config snapshot\n`);
                process.stdout.write(`  metrics.jsonl   — per-step loss + throughput\n`);
                process.stdout.write(`  model-card.md   — auto-generated model card\n`);
                process.stdout.write(`  README.md       — run wiki\n`);
                process.stdout.write(`\nRun \`infernet train status\` to review.\n`);
            } else {
                process.stderr.write(`error: training exited with code ${code} — see ${path.join(runDir, "run.log")}\n`);
            }
            resolve(code === 0 ? 0 : 1);
        });

        child.on("error", async (err) => {
            logStream.end();
            process.stderr.write(`error: ${err.message}\n`);
            await updateRunStatus(runDir, "failed", { error: err.message });
            resolve(1);
        });
    });
}

async function updateRunStatus(runDir, status, extra = {}) {
    const runFile = path.join(runDir, "run.json");
    try {
        const raw = JSON.parse(await fs.readFile(runFile, "utf8"));
        const updated = { ...raw, status, updated_at: new Date().toISOString(), ...extra };
        await fs.writeFile(runFile, JSON.stringify(updated, null, 2));
    } catch { /* best-effort */ }
}

async function findPython() {
    for (const bin of ["python3", "python"]) {
        try {
            await new Promise((resolve, reject) => {
                const c = spawn(bin, ["--version"], { stdio: "ignore" });
                c.on("close", (code) => code === 0 ? resolve() : reject());
                c.on("error", reject);
            });
            return bin;
        } catch { /* try next */ }
    }
    return null;
}

async function cmdStatus(args) {
    const positional = args.positional ?? [];
    const runId = positional[1]; // train status [run-id]
    const runsDir = getRunsDir();

    if (runId) {
        // Look for run.json in the given id or any output dir
        const candidates = [
            path.join(runsDir, runId, "run.json"),
            path.join(runId, "run.json"),
            path.join("output", "run.json"),
            "run.json"
        ];
        for (const p of candidates) {
            try {
                const run = JSON.parse(await fs.readFile(p, "utf8"));
                printRun(run);
                return 0;
            } catch { /* try next */ }
        }
        process.stderr.write(`Run ${runId} not found.\n`);
        return 1;
    }

    // Check ./output/run.json as default
    try {
        const run = JSON.parse(await fs.readFile("output/run.json", "utf8"));
        printRun(run);
        return 0;
    } catch { /* fall through */ }

    process.stdout.write("No active run found. Start one with `infernet train run`.\n");
    return 0;
}

function printRun(run) {
    process.stdout.write(`Run ID:  ${run.id}\n`);
    process.stdout.write(`Status:  ${run.status}\n`);
    process.stdout.write(`Started: ${run.started_at}\n`);
    if (run.updated_at) process.stdout.write(`Updated: ${run.updated_at}\n`);
    process.stdout.write(`Output:  ${run.output}\n`);
    process.stdout.write(`Config:  ${run.config}\n`);
}

async function cmdList() {
    // Check known locations for run.json files
    const searchDirs = ["output", "."];
    const runs = [];
    for (const d of searchDirs) {
        try {
            const run = JSON.parse(await fs.readFile(path.join(d, "run.json"), "utf8"));
            runs.push({ dir: d, ...run });
        } catch { /* skip */ }
    }
    if (runs.length === 0) {
        process.stdout.write("No runs found. Start one with `infernet train run`.\n");
        return 0;
    }
    const w = Math.max(8, ...runs.map((r) => r.id?.length ?? 0));
    process.stdout.write(`${"ID".padEnd(w)}  ${"STATUS".padEnd(12)} STARTED\n`);
    for (const r of runs) {
        process.stdout.write(`${(r.id ?? "?").padEnd(w)}  ${(r.status ?? "?").padEnd(12)} ${r.started_at ?? ""}\n`);
    }
    return 0;
}

async function cmdLogs(args) {
    const positional = args.positional ?? [];
    const target = positional[1] ?? "output";
    const logPath = path.join(target, "run.log");
    try {
        const content = await fs.readFile(logPath, "utf8");
        process.stdout.write(content);
    } catch {
        process.stderr.write(`No log found at ${logPath}\n`);
        return 1;
    }
    return 0;
}

async function cmdData(args) {
    const query = args.get("query") ?? args.get("q");
    if (!query) {
        process.stderr.write("error: --query <text> is required\n");
        process.stderr.write(`example: infernet train data --query "svelte 5 framework docs"\n`);
        return 2;
    }
    const apiKey = await resolveValueSerpKey();
    if (!apiKey) {
        process.stderr.write(
            "error: VALUESERP_API_KEY is not set.\n" +
            "Get a key at https://valueserp.com → set in env or in\n" +
            "~/.config/infernet/config.json under integrations.valueserp.api_key\n"
        );
        return 1;
    }
    const out = args.get("out") ?? args.get("output") ?? "./data/train.jsonl";
    const num = Number.parseInt(args.get("num") ?? "20", 10) || 20;
    const domains = args.get("domains")?.split(",").map((s) => s.trim()).filter(Boolean) ?? null;
    const minChars = Number.parseInt(args.get("min-chars") ?? "200", 10) || 200;
    const maxChars = Number.parseInt(args.get("max-chars") ?? "4000", 10) || 4000;

    process.stdout.write(`Searching ValueSerp for: "${query}"\n`);
    if (domains) process.stdout.write(`  domain whitelist: ${domains.join(", ")}\n`);

    const result = await buildTrainingDataset({
        query, apiKey, outPath: out, num, domains, minChars, maxChars,
        onProgress: ({ stage, index, total, url }) => {
            if (stage === "fetch") {
                process.stdout.write(`  [${index}/${total}] ${url}\n`);
            }
        }
    });

    process.stdout.write(`\n✓ Wrote ${result.examples} examples from ${result.urls} URLs to ${result.outPath}\n`);
    process.stdout.write(`\nNext steps:\n`);
    process.stdout.write(`  infernet train init --output ./run         # scaffold infernet.train.yml\n`);
    process.stdout.write(`  infernet train run  --local --output ./run # train against ${out}\n`);
    return 0;
}

export default async function train(args) {
    if (args.has("help") || args.has("h")) {
        process.stdout.write(HELP);
        return 0;
    }

    const positional = args.positional ?? [];
    const sub = positional[0];

    try {
        switch (sub) {
            case "data":
            case "crawl":
                return await cmdData(args);
            case "init":
                return await cmdInit(args);
            case "run":
            case "start":
                return await cmdRun(args);
            case "status":
            case "show":
                return await cmdStatus(args);
            case "list":
            case "ls":
                return await cmdList();
            case "logs":
            case "log":
                return await cmdLogs(args);
            default:
                process.stderr.write(sub
                    ? `unknown subcommand: ${sub}\n\n`
                    : "error: missing subcommand\n\n");
                process.stderr.write(HELP);
                return 2;
        }
    } catch (err) {
        process.stderr.write(`error: ${err?.message ?? err}\n`);
        return 1;
    }
}
