#!/usr/bin/env node
/**
 * Generate all the random secrets a fresh deployment needs.
 *
 * Outputs ready-to-paste env lines for:
 *   - INFERNET_CLI_SESSION_SECRET    (HMAC for CLI device-code JWTs)
 *   - CRON_SECRET                     (Bearer for /api/cron/* drain endpoints)
 *   - DID_VERIFICATION_KEY            (Ed25519 multibase public key for IPIP-0007)
 *   - DID_PRIVATE_KEY_BASE64          (the matching private key — store SAFELY)
 *
 * External-service keys (Supabase, CoinPay, NIM) are NOT generated —
 * those come from the respective dashboards.
 *
 * Usage:
 *   node tooling/generate-secrets.mjs               # print to stdout
 *   node tooling/generate-secrets.mjs >> .env       # append to env
 *   node tooling/generate-secrets.mjs --json        # machine-readable
 */

import { generateKeyPairSync, randomBytes } from "node:crypto";

// ---------------------------------------------------------------------------
// base58btc — minimal pure-JS implementation, matches the multibase 'z' prefix
// (same code style as coinpayportal/src/app/api/reputation/did/claim/route.ts)
// ---------------------------------------------------------------------------
function base58btcEncode(bytes) {
    const ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
    let num = BigInt("0x" + Buffer.from(bytes).toString("hex"));
    const result = [];
    while (num > 0n) {
        const mod = Number(num % 58n);
        result.unshift(ALPHABET[mod]);
        num = num / 58n;
    }
    for (const b of bytes) {
        if (b === 0) result.unshift("1");
        else break;
    }
    return result.join("");
}

function generateEd25519DidKey() {
    const { publicKey, privateKey } = generateKeyPairSync("ed25519");
    // Raw 32-byte ed25519 public key (drop the SPKI DER wrapper).
    const pubRaw = publicKey.export({ type: "spki", format: "der" }).subarray(-32);
    // Multicodec prefix for ed25519-pub is 0xed01.
    const multicodec = Buffer.concat([Buffer.from([0xed, 0x01]), pubRaw]);
    const multibase = "z" + base58btcEncode(multicodec);
    // Private key as PKCS8 DER → base64 (so it round-trips through env vars).
    const privDer = privateKey.export({ type: "pkcs8", format: "der" });
    const privBase64 = privDer.toString("base64");
    return { multibase, privBase64 };
}

const cliSessionSecret = randomBytes(32).toString("hex");
const cronSecret = randomBytes(32).toString("hex");
const did = generateEd25519DidKey();

const out = {
    INFERNET_CLI_SESSION_SECRET: cliSessionSecret,
    CRON_SECRET: cronSecret,
    DID_VERIFICATION_KEY: did.multibase,
    DID_PRIVATE_KEY_BASE64: did.privBase64
};

if (process.argv.includes("--json")) {
    process.stdout.write(JSON.stringify(out, null, 2) + "\n");
} else {
    const ts = new Date().toISOString();
    process.stdout.write(
        `# Generated by tooling/generate-secrets.mjs at ${ts}\n` +
        `# These are SECRETS — do not commit. .gitignore already covers .env.\n` +
        `# DID_PRIVATE_KEY_BASE64 is the matching key for DID_VERIFICATION_KEY —\n` +
        `# store somewhere encrypted (Doppler / 1Password / hardware token)\n` +
        `# rather than leaving it loose in .env on a long-lived box.\n\n` +
        `INFERNET_CLI_SESSION_SECRET=${out.INFERNET_CLI_SESSION_SECRET}\n` +
        `CRON_SECRET=${out.CRON_SECRET}\n` +
        `DID_VERIFICATION_KEY=${out.DID_VERIFICATION_KEY}\n` +
        `DID_PRIVATE_KEY_BASE64=${out.DID_PRIVATE_KEY_BASE64}\n`
    );
}
